#!/usr/bin/bash
function get_os() {
    for i in $(uname -a)
    do
        os=$i
    done
    echo $i
}
os=$(get_os)
argc=0
warns=true
for i in $*
do
	if [[ $i == "--help" ]] && [[ $argc -eq 0 ]] || [[ $i == "-h" ]] && [[ $argc -eq 0 ]]
	then
		echo 'Simple terminal based timer'
		echo 'Usage:'
		echo '--help   -h      Show this message'
		echo '--nowarn -n      Disable warnings'
		echo 'Examples:'
		echo 'msleep ~/sound.mp3 1:1:30  # 1 hour,1 minute,30 seconds,play ~/sound.mp3'
		echo 'msleep -n 2:45             # 2 minutes,45 seconds,disable warnings'
		echo 'msleep -n sound.mp3 5      # 5 seconds,play sound.mp3,disable warnings'
		break
	elif [[ $i == "--nowarn" ]] || [[ $i == "-n" ]]
	then
		warns=false
	elif [[ -e $i ]] || [[ -e $PWD/$i ]]
	then
		if [[ -e $i ]]
		then
			sound=$i
		else
			sound="$PWD/$i"
		fi
	elif [[ $i =~ [0-9]+(:[0-9]+(:[0-9]+)?)? ]]
	then
		time_of=0
		tmpifs=$IFS
		IFS=":"
		index=0
		for j in $i
		do
			index=$((index+1))
		done
		case $index in
			1)
				for j in $i
				do
					time_of=$((time_of+j))
				done
			;;
			2)
				index=0
				for j in $i
				do
					if [[ $index -eq 0 ]]
					then
						j=$((j*60))
					fi
					time_of=$((time_of+j))
					index=$((index+1))
				done
			;;
			3)
				index=0
				for j in $i
				do
					if [[ $index -eq 0 ]]
					then
						j=$((j*3600))
					elif [[ $index -eq 1 ]]
					then
						j=$((j*60))
					fi
					time_of=$((time_of+j))
					index=$((index+1))
				done
			;;
		esac
		IFS=$tmpifs
		sleep $time_of
		if [[ -n $sound ]]
		then
			if [[ $os == "Android" ]]
			then
				if $warns
				then
					echo "Playing sounds is not supported on Android"
				fi
			else
				if command -v mpg123
				then
					mpg123 $sound
				else
					if $warns
					then
						echo "The program 'mpg123' not found. Install it first"
					fi
				fi
			fi
		fi
		break
	fi
	argc=$((argc+1))
done
