#!/usr/bin/bash
sound_player=mpg123 # config
notify=false
notify_isnt_set=true # Do not change this variable
function usage() {
	echo 'Simple terminal based timer written in Bash'
	echo 'Usage:'
	echo '   --help    -h    Show this message'
	echo '   --version -v    Show version'; echo
	if $notify
	then
		echo '   --notify  -n    Disable notification'
	else
		echo '   --notify  -n    Enable notification'
	fi
	echo; echo 'Examples:'
	echo ' msleep ~/sound.mp3 1:1:30  # 1 hour,1 minute,30 seconds,play ~/sound.mp3'
	echo ' msleep -n 2:45             # 2 minutes,45 seconds,send notification'
	echo ' msleep sound.mp3 5         # 5 seconds,play sound.mp3'
}
if [[ -z $1 ]]
then
	usage
fi
for i in $*
do
	if [[ $i == "--help" ]] || [[ $i == "-h" ]]
	then
		usage
		break
	elif [[ $i == "--version" ]] || [[ $i == "-v" ]]
	then
		echo "1.2.0"
		break
	elif [[ $i == "--notify" ]] && $notify_isnt_set || [[ $i == "-n" ]] && $notify_isnt_set
	then
		if $notify
		then
			notify=false
		else
			notify=true
		fi
		notify_isnt_set=false
	elif [[ -e $i ]] || [[ -e $PWD/$i ]]
	then
		if [[ -e $i ]]
		then
			sound=$i
		else
			sound="$PWD/$i"
		fi
	elif [[ $i =~ [0-9]+(:[0-9]+(:[0-9]+)?)? ]]
	then
		time_of=0
		tmpifs=$IFS
		IFS=":"
		index=0
		for j in $i
		do
			index=$((index+1))
		done
		case $index in
			1)
				for j in $i
				do
					time_of=$((time_of+j))
				done
			;;
			2)
				index=0
				for j in $i
				do
					if [[ $index -eq 0 ]]
					then
						j=$((j*60))
					fi
					time_of=$((time_of+j))
					index=$((index+1))
				done
			;;
			3)
				index=0
				for j in $i
				do
					if [[ $index -eq 0 ]]
					then
						j=$((j*3600))
					elif [[ $index -eq 1 ]]
					then
						j=$((j*60))
					fi
					time_of=$((time_of+j))
					index=$((index+1))
				done
			;;
		esac
		sleep $time_of
		IFS=$tmpifs
		if $notify
		then
			if command -v notify-send
			then
				notify-send "Msleep: Time $i is out"
			else
				echo "Msleep: Time $i is out"
			fi
		fi
		if [[ -n $sound ]]
		then
			$sound_player $sound
		fi
		break
	fi
done
